### ISSUE TITLE
Space in Alias-field results in error

### ISSUE THREAD

**Issue by DisplayMhb** [KOBENDigital/IPRestrictor#2]
If the Alias field includes a space, the ips.data is no longer readable (I'm guessing since the file reader splits by space to find alias, ip-from, and ip-to).

There should be some validation to ensure that spaces cannot be entered in the Alias field (or the file reader should be changed to be able to handle spaces in Alias).

Tested in clean Umbraco 7.7.8 assembly: 1.0.6582.14881

**Comment by skartknet** [comment]
Added some checkings and removal of spaces on alias
