### ISSUE TITLE
Duplicates in Alias gives Angular warning in console, but is still added to list

### ISSUE THREAD

**Issue by DisplayMhb** [KOBENDigital/IPRestrictor#4]
If I add an entry with an alias that still exists, I get a warning that duplicates aren't allowed, and when I change the ip address of the duplicate alias entry, the existing entry with the same alias is updated in the ip list -- but if I click Save and go away and back to the IPRestrictor form, the duplicate is added to the list.

Tested in clean Umbraco 7.7.8 assembly: 1.0.6582.14881

**Comment by skartknet** [comment]
Fixed on 97fb9f26aa0c22b747905b761b93e104353c5e2c
